name: parentsecole
description: Une application pour les parents d'élèves

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.5
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.11.0
  intl: any
  fl_chart: ^1.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Supprimez ou corrigez la section fonts si elle existe
  # fonts:
  #   - family: ...

  assets:
    - assets/images/